### ISSUE TITLE
Carthage: CLI error when trying to create video categories

### ISSUE THREAD

**Issue by freakstatic** [Joystream/joystream#4119] opened 2022-08-03 20:43 UTC
`yarn run joystream-cli content:createVideoCategory` is giving the following error 

```
Initializing the query node connection (https://54.172.154.45.nip.io/query-node/server/graphql)...... done
Initializing the api connection (wss://54.172.154.45.nip.io/ws-rpc)...... done
Derived context: Lead
{
    name: "Film & Animation"
}
? Do you confirm the provided input? Yes

Sending contentWorkingGroup.leadRemark extrinsic from Bob__5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty__DEV...
Tx params: [ [ '0x0a1046696c6d202620416e696d6174696f6e' ] ]
? Tx fee of 64.2022 mJOY will be deduced from you account, do you confirm the transfer? Yes
Extrinsic successful!
    TypeError: Cannot read property 'toString' of undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also it seems that it's being created `leadRemark` transaction and not a `createVideoCategory` transaction
https://polkadot.js.org/apps/?rpc=wss://54.172.154.45.nip.io/ws-rpc#/explorer/query/0xc3a5a6bdc75b9268832daa098ad7e4ff3dfbc6f556e7e7ae851e984b9ca32da1

was this transaction type removed from Carthage?
https://github.com/Joystream/joystream/commit/91ee3bede00e24178c41cd2cba9ef78420e59c1d

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202768831762686) by [Unito](https://www.unito.io)

**Comment by freakstatic** [comment] 2022-08-03 20:48
FYI the error happens in this line
https://github.com/Joystream/joystream/blob/917365f9931333a0feba1654737923d7cff56ccb/cli/src/commands/content/createVideoCategory.ts#L47
`categoryId` is null so `.toString()` fails here

**Comment by freakstatic** [comment] 2022-08-04 14:16
@dmtrjsg reported that this is related with this issue: 
https://github.com/Joystream/joystream/pull/4026

**Comment by dmtrjsg** [comment] 2022-08-09 09:18
@freakstatic fyi the superceding PR is opened now, so closing 4026, but the issue is not resolved just yet.
- https://github.com/Joystream/joystream/pull/4122

Eta on above today or tomorrow.

**Comment by dmtrjsg** [comment] 2022-08-09 10:10
@kdembler pls weigh in on the above.

**Comment by kdembler** [comment] 2022-08-09 10:14
Hey @freakstatic, so the bottom line is that we are making some changes to categories in Carthage and they are not all fully implemented yet. How the system will work after changes (https://github.com/Joystream/joystream/pull/4122):
1. Channel categories are removed completely
2. Video categories are removed as an on-chain identity, and are managed on metaprotocol (QN) level using `memberRemark` extrinsics
3. Anyone (member) will be free to create a category, it will no longer be restricted to only leads

I will ping you once the new CLI is available

**Comment by freakstatic** [comment] 2022-08-09 19:15
> Hey @freakstatic, so the bottom line is that we are making some changes to categories in Carthage and they are not all fully implemented yet. How the system will work after changes (#4122):
> 
> 1. Channel categories are removed completely
> 2. Video categories are removed as an on-chain identity, and are managed on metaprotocol (QN) level using `memberRemark` extrinsics
> 3. Anyone (member) will be free to create a category, it will no longer be restricted to only leads
> 
> I will ping you once the new CLI is available

Hi @kdembler!
Thanks for the detailed explanation, that makes sense to allow a better distribution of the work

**Comment by kdembler** [comment] 2022-08-17 09:33
@freakstatic New categories system is now merged into `carthage`, closing this issue

**Closed as completed by kdembler** 2022-08-17 09:33 UTC
