### ISSUE TITLE
Add proposal for toggling nft limits

### ISSUE THREAD

**Issue by dobertRowneySr** [Joystream/joystream#4645] opened 2023-02-17 14:13 UTC
Add a proposal to execute the `toggle_nft_limits` extrinsic, which enables/disables the whole limiting functionality

**Comment by traumschule** [comment] 2023-09-06 15:00
duplicate of #3989?

**Comment by kdembler** [comment] 2024-04-12 14:00
Duplicate of https://github.com/Joystream/joystream/issues/3989

**Closed as completed by kdembler** 2024-04-12 14:00 UTC
Labels: content-pallet, runtime, urgent-post-mainnet
