### ISSUE TITLE
Alexandria: Key generation

### ISSUE THREAD

**Issue by bwhm** [Joystream/joystream#1383] opened 2020-09-16 12:44 UTC
When we ran the first test, lots of keys were generated in pioneer for each of the testers.
Some were also imported from running testnet.

When we launched the second test, with same url for pioneer, some keys were still "there" but a lot of them were gone. They still exist in local storage, but they are not shown to the user.

Here are the three types of tested:
1. Keys imported from actual running testnet
2. Keys created in pioneer using "add account"
3. Keys created in pioneer automatically by applying for a role (the "role key")

Only the ones from "3." was displayed in pioneer.

I did some research, and created new keys without setting a password:
#### From 1. 
sr key .json file:
```
{"address":"5GZYTuC9S5mUjPFAJoEHNj2NdcgabjuhmYAjeHaWZM64RFod","encoded":"0x3053020101300506032b6570042204202074a41b276960ce99d3ecfbdc266c0e0dd25f09e1cb33fa58dacebc1b4ad77422b52664e52d1d944254acf0353c16d326e7f2dce86ee721f348418ca6ae2a21a123032100c6ef6eb0e60dc5fe0d6ee2072be6d746882def9551c61db4bc1d34b66c26d420","encoding":{"content":["pkcs8","sr25519"],"type":"none","version":"2"},"meta":{"name":"sr-key","tags":[],"whenCreated":1600258195404}}
```
ed key .json file:
```
{"address":"5FpjwJDbW7jLTwgAHesAvurTeshQ6HisAi6EFqo48CRJgQb1","encoded":"0x3053020101300506032b6570042204202d952efd931b55531a646f24c1caba79fa95eb08fab5bedebf70a567c7190988a64a7fd96e75b2a6eb48439a12ed62d9c21f9346eb5df7cd721aa92f07c3726da123032100a64a7fd96e75b2a6eb48439a12ed62d9c21f9346eb5df7cd721aa92f07c3726d","encoding":{"content":["pkcs8","ed25519"],"type":"none","version":"2"},"meta":{"name":"ed-key","tags":[],"whenCreated":1600259396709}}
```

#### From 2.
Applied for a role on alexandria test 2 (defaults to ed):
```
{"address":"5C4jVQmRFSc5VM9SVvfUvRDDJu4r1ZcvNfVvXVmCirUCjKfG","encoded":"MFMCAQEwBQYDK2VwBCIEICtfOrMqH79+RzrMkScnU4g0oizncvvvcObl8+3ZehQMAAV/sDl6Fqi23XA4m+wo055+/+JEyq8Ti76Xb0VfluChIwMhAAAFf7A5ehaott1wOJvsKNOefv/iRMqvE4u+l29FX5bg","encoding":{"content":["pkcs8","ed25519"],"type":["none"],"version":"3"},"meta":{"name":"storage dude role key","tags":[],"whenCreated":1600086123974}}
```

#### From 3.
sr key, with "only this network":
```
{"address":"5DP53HktQwntHGLu73rok3RyEurNijKoHzoVx1JCEomNRZBk","encoded":"MFMCAQEwBQYDK2VwBCIEINC1yfue9TS9D1FZAEHY9uiJA5IXluVjzBb5dBh17pRarnPnGKvZbsw2uD/1K1sx5WQyVgmjxAOOVKsXRpAQS2KhIwMhADo99Z/fA2e9GnUUhFbazUEgeA165a316/tm9H2X7ewV","encoding":{"content":["pkcs8","sr25519"],"type":["none"],"version":"3"},"meta":{"genesisHash":"0xb717c893ce20bebfb435ab9869d69f59f843cc945d7b5a802e5bea0f1712833d","name":"sr","tags":[],"whenCreated":1600258150742}}
```
same key, but toggling off "only this network":
```
{"address":"5DP53HktQwntHGLu73rok3RyEurNijKoHzoVx1JCEomNRZBk","encoded":"MFMCAQEwBQYDK2VwBCIEINC1yfue9TS9D1FZAEHY9uiJA5IXluVjzBb5dBh17pRarnPnGKvZbsw2uD/1K1sx5WQyVgmjxAOOVKsXRpAQS2KhIwMhADo99Z/fA2e9GnUUhFbazUEgeA165a316/tm9H2X7ewV","encoding":{"content":["pkcs8","sr25519"],"type":["none"],"version":"3"},"meta":{"genesisHash":null,"name":"sr","tags":[],"whenCreated":1600258150742}}
```
ed (with/without)
```
{"address":"5DvxnMtpx9yA2KbyHpFoVF7H18Jf5phQPWrAM5SWThopPGxN","encoded":"MFMCAQEwBQYDK2VwBCIEIMTBixxTtgbHGcSFtdZYsxU6T2zeEpY3nBXfYg8pAvmZUpC/hxD02uUsC9Q3U89PFsKCg7eVlWPyRkFOrFdkMNGhIwMhAFKQv4cQ9NrlLAvUN1PPTxbCgoO3lZVj8kZBTqxXZDDR","encoding":{"content":["pkcs8","ed25519"],"type":["none"],"version":"3"},"meta":{"genesisHash":"0xb717c893ce20bebfb435ab9869d69f59f843cc945d7b5a802e5bea0f1712833d","name":"ed","tags":[],"whenCreated":1600259679673}}
---
{"address":"5DvxnMtpx9yA2KbyHpFoVF7H18Jf5phQPWrAM5SWThopPGxN","encoded":"MFMCAQEwBQYDK2VwBCIEIMTBixxTtgbHGcSFtdZYsxU6T2zeEpY3nBXfYg8pAvmZUpC/hxD02uUsC9Q3U89PFsKCg7eVlWPyRkFOrFdkMNGhIwMhAFKQv4cQ9NrlLAvUN1PPTxbCgoO3lZVj8kZBTqxXZDDR","encoding":{"content":["pkcs8","ed25519"],"type":["none"],"version":"3"},"meta":{"genesisHash":null,"name":"ed","tags":[],"whenCreated":1600259679673}}
```
ecdsa (with/without)
```
{"address":"5Hp8y8BjBuCCFPuNm7rkhMxiHkMWHEXGt77Kgwty1gtTjbrN","encoded":"MFMCAQEwBQYDK2VwBCIEIFeu5HxvUfmo0ug+N1747SLR5GlS98pUbHLqsanKMCCPoSMDIQACWNWCNqozsowzxzmNwTAh+p4nIhadKDcW0Z8mYbrOVPs=","encoding":{"content":["pkcs8","ecdsa"],"type":["none"],"version":"3"},"meta":{"genesisHash":"0xb717c893ce20bebfb435ab9869d69f59f843cc945d7b5a802e5bea0f1712833d","name":"ecdsa","tags":[],"whenCreated":1600259767545}}
---
{"address":"5Hp8y8BjBuCCFPuNm7rkhMxiHkMWHEXGt77Kgwty1gtTjbrN","encoded":"MFMCAQEwBQYDK2VwBCIEIFeu5HxvUfmo0ug+N1747SLR5GlS98pUbHLqsanKMCCPoSMDIQACWNWCNqozsowzxzmNwTAh+p4nIhadKDcW0Z8mYbrOVPs=","encoding":{"content":["pkcs8","ecdsa"],"type":["none"],"version":"3"},"meta":{"genesisHash":null,"name":"ecdsa","tags":[],"whenCreated":1600259767545}}
```
#### Problem
It appears that only keys generated with `version=3` and `genesisHash=null` are "remembered".

This could be quite the problem, as it would mean all the users keys would disappear. They can recover them, but it will require lots of effort.

#### Solution
Steps:
i. Verify this is correct
ii. Make new keys generated default to `genesisHash=null` on new network (not sure if we want this to be "linked" with whether the user enables/disables "only this network"
iii. Have pioneer accept all keys in local storage, regardless of `version`, `keytype` and `genesisHash`

I'm not sure whether to assign this to @mnaamani or @Lezek123 .
i. seems easier for the former, whereas the rest is most likely easier for the latter?

**Comment by bwhm** [comment] 2020-09-16 13:02
Thinking about this more, we should probably test/verify how both the `storage-node` and the `cli` handles this...

**Comment by mnaamani** [comment] 2020-09-17 06:37
I fixed it by just adding extra `/` at the end to be more explicit

`import Transport from '@polkadot/joy-utils/transport/';`

**Comment by mnaamani** [comment] 2020-09-17 09:00
Okay did some testing in pioneer and I can confirm your results.
I tested by using pioneer on `localhost:3000/` (to use the same localstorage) and switching between different chains.

When a key with genesis hash set to the chain value is imported, indeed it is saved and switching to another endpoint/chain pioneer will not load it into active keys list (although it is still in local storage) - funnily also you can import a key for a different geneis and you will see the key imported into the list, but after refreshing the page it will go away.

I confirmed that keys that are currently in v2, do not have genesis hash in metadata and are successfully loaded in new pioneer. So all keys will be "remembered" when we switch to new pioneer and remain on `testnet.joystream.org` domain.
I am also able to restore keys from json exported in v2 to the new pioneer.

So for the initial launch we will not have issues with anyone loosing keys.

After launch of Alexandria of course when new keys are generated or exported they will be in the new v3 format and user may optionally choose "only this network". And we will only get an issue with keys not being loaded when switching between networks or if/when we launch a new chain.

So for end users and for purpose of launch, I don't see an immediate need to change behavior of how keys are loaded from localstorage, but there is a certainly room for confusion for anyone doing testing and switching between chains while using pioneer from the same url.

I will look at pioneer codebase now and identify how to implement solution points `ii` and `iii`

**Comment by mnaamani** [comment] 2020-09-17 09:02
> Thinking about this more, we should probably test/verify how both the `storage-node` and the `cli` handles this...

will investigate this also to see also if it could be an issue.

**Comment by Lezek123** [comment] 2020-09-17 09:08
I investigated the Pioneer and `@polkadot/ui-keyring` codebase a little and I think we can skip the `genesisHash` check by modyfing `keyring.loadAll` call in `pioneer/packages/react-api/src/Api.tsx` (if needed):
```
  keyring.loadAll({
    // genesisHash: api.genesisHash, <---- Skip genesis hash filter
    isDevelopment,
    ss58Format,
    store,
    type: 'ed25519'
  }, injectedAccounts);
```

**Comment by bwhm** [comment] 2020-09-17 09:12
> I investigated the Pioneer and `@polkadot/ui-keyring` codebase a little and I think we can skip the `genesisHash` check by modyfing `keyring.loadAll` call in `pioneer/packages/react-api/src/Api.tsx` (if needed):
> 
> ```
>   keyring.loadAll({
>     // genesisHash: api.genesisHash, <---- Skip genesis hash filter
>     isDevelopment,
>     ss58Format,
>     store,
>     type: 'ed25519'
>   }, injectedAccounts);
> ```

wonderful!
I assume it's the same for `sr25519`?

Follow ups:
- Are there any checks for `version`?
- Does it even look for the new `ecdsa` key-type?

**Comment by mnaamani** [comment] 2020-09-17 09:16
`type: 'ed25519'` there I think is just the default key type when generating new keys probably.

**Comment by Lezek123** [comment] 2020-09-17 09:23
> Are there any checks for version?

Didn't notice any. The keys with `version: 2` work succesfully.

> type: 'ed25519' there I think is just the default key type when generating new keys probably.

I think it's the type that the keys default to (when loaded) if there is no type specified in the stored `json` (otherwise it uses the type that is in the json, which is always(?) the case)

**Comment by mnaamani** [comment] 2020-09-17 09:28
So pioneer is using the [@polkadot/ui-keyring](https://github.com/polkadot-js/ui/blob/master/packages/ui-keyring/src/Keyring.ts#L249) which deals with genesis hash etc.. 

Colossus just uses the lower level `@polkadot/kerying` library so there will be no issues there.

**Comment by mnaamani** [comment] 2020-09-17 09:34
> > I investigated the Pioneer and `@polkadot/ui-keyring` codebase a little and I think we can skip the `genesisHash` check by modyfing `keyring.loadAll` call in `pioneer/packages/react-api/src/Api.tsx` (if needed):
> > ```
> >   keyring.loadAll({
> >     // genesisHash: api.genesisHash, <---- Skip genesis hash filter
> >     isDevelopment,
> >     ss58Format,
> >     store,
> >     type: 'ed25519'
> >   }, injectedAccounts);
> > ```
> 

I can confirm based on [this](https://github.com/polkadot-js/ui/blob/8525c59b9ada31156c637192e6adb08b10fa7f68/packages/ui-keyring/src/Keyring.ts#L233) that will work.

**Comment by mnaamani** [comment] 2020-09-17 09:44
The suggested solution by @Lezek123 looks fine.

**Comment by Lezek123** [comment] 2020-09-17 09:50
Created a PR: https://github.com/Joystream/joystream/pull/1390

**Comment by mochet** [comment] 2020-09-18 20:10
> After launch of Alexandria of course when new keys are generated or exported they will be in the new v3 format and user may optionally choose "only this network". And we will only get an issue with keys not being loaded when switching between networks or if/when we launch a new chain.

I didn't see it mentioned so far, but I'll mention it because maybe its important...
* Current testnet behavior is when a key is created it has the default property of  `use on any network`
![image](https://user-images.githubusercontent.com/50830161/93640899-689ea380-fa0c-11ea-8626-2aed0a895547.png)

* Alexandria currently has the default behavior of `only this network`
![image](https://user-images.githubusercontent.com/50830161/93640819-44db5d80-fa0c-11ea-8ddb-7637f259cfb1.png)


These are freshly created keys, but this is the default behavior a user will experience on the platform.

Just thought it would be important to point this out.

**Comment by Lezek123** [comment] 2020-09-22 07:54
Resolved in https://github.com/Joystream/joystream/pull/1390

Thanks for pointing it out @mochet, we actually removed _only on this network_ option entirely, as we decided to load all keys from the local storage regardless of `genesisHash` (to avoid exluding any potential previous chain keys), so this setting wouldn't apply anymore.

**Closed as completed by Lezek123** 2020-09-22 07:54 UTC
