### ISSUE TITLE
Query node support for creator payout proposal

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#2941] opened 2021-12-17 14:42 UTC
SSIA

```Rust
pub struct UpdateChannelPayoutsParametersRecord<ChannelPayoutsPayloadParameters, Balance, Hash> {
    pub commitment: Option<Hash>,
    pub payload: Option<ChannelPayoutsPayloadParameters>,
    pub min_cashout_allowed: Option<Balance>,
    pub max_cashout_allowed: Option<Balance>,
    pub channel_cashouts_enabled: Option<bool>,
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1202778227580928) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment] 2022-08-10 15:29
duplicate of 
- https://github.com/Joystream/joystream/issues/3613

**Closed as completed by dmtrjsg** 2022-08-10 15:29 UTC
Labels: proposal-system, query-node, scope:pioneer-support, duplicate, scope:channel-payouts, must-have
