### ISSUE TITLE
Pioneer: Runtime Proposal page heavy lag + proposed fix

### ISSUE THREAD

**Issue by mochet** [Joystream/joystream#651] opened 2020-06-10 09:02 UTC
Currently the Runtime Proposal page causes a lot of lag for most users, this is because it reportedly calculates the hash on the browser on page load.
A user usually has to wait upwards of 5 minutes for the page to stabilize, even if they want to just check the status of current votes. The page becomes almost completely unresponsive while this happens.

An example is the current runtime proposal vote here: https://testnet.joystream.org/#/proposals/14

This is preventing users from voting or turning away users from voting on the current runtime upgrade proposal as they think the page is broken.

One suggestion to fix this issue would be to make the hash calculation only happen after a user has clicked a button, this is done on some routers, like the below pictures demonstrate:
![image](https://user-images.githubusercontent.com/50830161/84248355-5f06c500-ab1a-11ea-812a-1c1c9d95c5d9.png)
![image](https://user-images.githubusercontent.com/50830161/84248362-60d08880-ab1a-11ea-8b9a-11ad54cb7e5f.png)

**Comment by bedeho** [comment] 2020-06-11 09:41
I think this is a great idea, perhaps @Lezek123 can fix?

**Comment by mnaamani** [comment] 2020-06-11 09:48
In addition to the delay in calculating the hash, I expect there is also a short delay in downloading the ~1.4MB code as well, but I'm not sure how significant that is, it would depend on the user's bandwidth and specs.

Consider using background workers to do the check asynchronously?

**Comment by mnaamani** [comment] 2020-06-11 09:50
In future we might even have to consider storing the code in a separate state storage so the code can be downloaded only if user chooses to verify.

**Comment by Lezek123** [comment] 2020-06-11 10:11
I think this lag may be caused by the call to `api.query.proposalsCodex.proposalDetailsByProposalId(RUNTIME_PROPOSAL_ID)` itself (which can be also observed on https://testnet.joystream.org/#/chainstate currently with proposal id === `14`).

The details of runtime updrade proposal consist only of the full WASM file binary data, which has to be downloaded and decoded when this call is made. We can probably skip making this call until the user asks to verify the data (ie. using the button as proposed).

**Comment by Lezek123** [comment] 2020-07-30 10:48
I consider it fixed in https://github.com/Joystream/joystream/pull/957 (although the possibilities for optimalization are still kind of limited without the query node)

**Closed as completed by Lezek123** 2020-07-30 10:48 UTC
Labels: enhancement, good first issue, estimate-3h, nicaea, feedback
