### ISSUE TITLE
QN support for Playlists

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/joystream#3244] opened 2022-02-16 17:40 UTC
### Context

Playlists [insert brief]
[insert design epic]
[insert dev epic]

- Keep in mind that while playlists exist, in some reduced form, in the runtime, they should be implemented as metaprotocol by tech team, by overloading the on-chain video entity, as described
- here Unlock off-chain overloading of video joystream#2739.
- There is therefore obviously no query node support for this now.
- What metadata should a playlist have? I think simply a name+description is sufficient and ordered list of contained videos is fine?
- As a result of the prior point, one will technically be able to issue NFTs against playlists, as distinct from possible NFTs on the individual videos in the list. I think we should follow the same mutation rules as for proper videos: if there is an NFT issued, all metadata is immutable, hence it means title and contained video order and videos cannot be updated by channel operator.
- Playlist can only hold videos from the same channel, and, if the video is deleted, the playlist still exists,
- A video can be part of more than one playlist.

### Scope

QN mappings for Playlist functionality

- [ ] tbd

**Comment by kdembler** [comment] 2022-03-07 16:54
Duplicate of https://github.com/Joystream/joystream/issues/3245

**Closed as completed by kdembler** 2022-03-07 16:54 UTC
Labels: query-node
