### ISSUE TITLE
Flexibile working period duration

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream#3193] opened 2022-02-08 22:04 UTC
# Background

Currently, the working period for a bounty lasts for a fixer period of time from when the funding period is over. The problem with this is that

a. it may be hard to anticipate up-front during bounty creation, how long it will take for the right worker to show up and discover the bounty, in particular because the funding period can itself be highly variable in duration.
b. there may be one or more false starts where a worker begins, which may deter others, but then pulls out, while consuming parts of the working period.
c. there may be complications relating to the nature of the work, or the ability of an otherwise suitable candidate to perform the work.

At the same time, the total lack of constraints around the working period does leave the possible third party contributors at the mercy of the oracle in terms of not locking up their funds perpetually.

# Proposal

1. Allow bounties to be created with perpetual working periods, then backers at least know this up front. This will likely impact the whole slashing logic of entries that withdraw, probably should just be dropped in this type of bounty.
2. Same as 1, but also allow council to intervene and terminate a bounty in the working period (e.g. because the oracle becomes hostile or idle), basically equivalent effect as judgement period expiring.

**Comment by L3pereira** [comment] 2022-02-09 08:35
> 2. Same as 1, but also allow council to intervene and terminate a bounty in the working period (e.g. because the oracle becomes hostile or idle), basically equivalent effect as judgement period expiring.

In the case of a bounty being created by a working leader (#2979) , would he be able to end the bounty as well? 
One of the reasons a working group exists, is to free the council from the day to day decisions that happens in the sub systems.

**Comment by bedeho** [comment] 2022-02-09 08:44
> In the case of a bounty being created by a working leader (https://github.com/Joystream/joystream/issues/2979) , would he be able to end the bounty as well?
One of the reasons a working group exists, is to free the council from the day to day decisions that happens in the sub systems.

Very good observation, while in spirit you are correct, I think its best to just keep it simpler and have the council be the only source of such overriding - we already have so many edge cases, but if the lead makes such a proposal for a bounty they made, this will likely carry a lot of weight, so it should not be a problem.

**Comment by L3pereira** [comment] 2022-02-09 09:27
>  I think its best to just keep it simpler and have the council be the only source of such overriding - we already have so many edge cases, 

yes we would be lost in a storm of possibilities, it's hard to predict and put in code all the incentives people have to behave well or bad, and  set a system that is open and safe.

**Comment by L3pereira** [comment] 2022-02-15 16:19
The extrinsic that terminates a perpetual bounty, withdraws the funds of all funders + a cherry fraction.
This extrinsic should also unlock the entrant stake amount for all workers staking accounts, **present in that specific bounty**.
The problem is that the work entries, are a simple map that aggregates all the entries for all bounties, I cannot know which bounty an entry belongs.
submit_oracle_judgment extrinsic presumes that you know those entities a prior and accepts that as a parameter 

```rust
decl_storage! {
    trait Store for Module<T: Trait> as Bounty {
        /// Bounty storage.
        pub Bounties get(fn bounties) : map hasher(blake2_128_concat) T::BountyId => Bounty<T>;

        /// Double map for bounty funding. It stores a member or council funding for bounties.
        pub BountyContributions get(fn contribution_by_bounty_by_actor): double_map
            hasher(blake2_128_concat) T::BountyId,
            hasher(blake2_128_concat) BountyActor<MemberId<T>> => BalanceOf<T>;

        /// Count of all bounties that have been created.
        pub BountyCount get(fn bounty_count): u32;

        /// Work entry storage map.
        pub Entries get(fn entries): map hasher(blake2_128_concat) T::EntryId => Entry<T>;

        /// Count of all work entries that have been created.
        pub EntryCount get(fn entry_count): u32;
    }
}
```
This
``` rust
        /// Work entry storage map.
        pub Entries get(fn entries): map hasher(blake2_128_concat) T::EntryId => Entry<T>;
```
Should be similar to this right?
``` rust
        /// Double map for bounty funding. It stores a member or council funding for bounties.
        pub BountyContributions get(fn contribution_by_bounty_by_actor): double_map
            hasher(blake2_128_concat) T::BountyId,
            hasher(blake2_128_concat) BountyActor<MemberId<T>> => BalanceOf<T>;
```
Something like 
``` rust

        pub Entries get(fn entries): double_map
            hasher(blake2_128_concat) T::BountyId,
            hasher(blake2_128_concat) T::EntryId => Entry<T>;
```
Or

``` rust
pub struct EntryRecord<AccountId, MemberId, BlockNumber, Balance, BountyId> {
   /// Bounty ID.
   pub bounty_id: BountyId,    <----------------------------------

    /// Work entrant member ID.
    pub member_id: MemberId,

    /// Account ID for staking lock.
    pub staking_account_id: AccountId,

    /// Work entry submission block.
    pub submitted_at: BlockNumber,

    /// Signifies that an entry has at least one submitted work.
    pub work_submitted: bool,

    /// Optional oracle judgment for the work entry.
    /// Absent value means neither winner nor rejected entry - "legitimate user" that gets their
    /// stake back without slashing but doesn't get a reward.
    pub oracle_judgment_result: Option<OracleWorkEntryJudgment<Balance>>,
}
```

**Comment by bedeho** [comment] 2022-02-15 17:29
Replied in DM, but basically: termination should not attempt to do automated cleanup, this is not feasible in this module, just follow the same state transitiona as what is done in extrinsic `submit_oracle_judgement` when there are no winners.

**Comment by L3pereira** [comment] 2022-02-21 08:50
Do we relly need  the has_contributions flag?

```rust
pub enum BountyStage {
    /// Bounty funding stage.
    Funding {
        /// Bounty has already some contributions.
        has_contributions: bool,
    },
   ...
}
```

Why can't we use the total_funding in the bounty record
```rust
pub struct BountyRecord<Balance, BlockNumber, MemberId: Ord> {

    pub creation_params: BountyParameters<Balance, BlockNumber, MemberId>,

    /// Total funding balance reached so far.
    /// Includes initial funding by a creator and other members funding.
    pub total_funding: Balance, <-----------------------------------------------------------

    pub milestone: BountyMilestone<BlockNumber>,
    pub active_work_entry_count: u32,
}
```
if the bounty has a total funding > 0 it's because it has contributions

it would simplify the stages 

```rust
pub enum BountyStage {
    /// Bounty funding stage.
    Funding,
   ...
}
```

**Comment by bedeho** [comment] 2022-02-21 15:25
1. Briefly looked into this, so my _guess_ is that it is added to `BountyStage` to make it more convenient to work with, becuase there are a bunch of helper functions that try to do computation only using this stage, and so this helps make that a simple self-contained representation of what is going on for the prupose of transaction processing. This is not a big deal, because the type `BountyStage` itself has not redundancy and there is no state redundancy, as `BountyStage` is not stored in storage state.
2. This does raise the more deeper question of why `BountyMilestone::Created` does have `has_contributions`, because it is stored as part of the `BountyRecord`, and that would be a problematic redundancy. I don't know off the top of my head, and I could not quickly find out, perhaps @shamil-gadelshin can weigh in on this at some point.
3. Most importantly: this is really a change which is 100% unrelated to the work we are trying to do here with the working periods and everything else, so we should not try to resolve this now, instead, open a new issue where this question is asked, and then it can be processed later.

**Comment by L3pereira** [comment] 2022-02-23 16:00
@bedeho 

When doing the ```withdraw_contributor_funds``` extrinsic tests, I found it impossible to have a ```FailedBountyWithdrawal``` stage without some state inside, indicating which path the bounty has taken.
This is useful, to know to who the ```oracle reward``` or ```cherry``` should be transferred.

I tried to avoid this by having these transfers take place in the stages before.
Eg: when I finish (as an oracle) the working period by calling the new extrinsic ```end_working_period```, I can at the end of this function, return the oracle to the creator in case there are no active work entries. 
After that when the oracle calls ```submit_oracle_judgement``` he can return the ```oracle reward``` to the creator if the judgement has no winners or take the reward to himself otherwise.
This frees ```withdraw_contributor_funds``` from having to decide who the reward or cherry should go to, based on the path the bounty took to reach the ```FailedBountyWithdrawal``` stage, not only that, but It's fairer since doesn't expose the creator to the will of the funders (even if they have an incentive to call ```withdraw_contributor_funds```).

The problem arises in one branch when the funding period expires, the current funding is less than the minimum needed and there is at least one contributor. 
In this case, there is no intermediate stage in between funding and  ```FailedBountyWithdrawal```. Unlike the other situations, there is only one extrinsic to be called, I have to decide the reward destination inside the ```withdraw_contributor_funds```,
this means I have to know why the stage is ```FailedBountyWithdrawal```

What do you think if we have a specific extrinsic, so the creator can withdraw the oracle reward?
In the end with new extrinsic or not, I need more info about the stages.

**Comment by L3pereira** [comment] 2022-02-23 17:34
I solved the issue, but I think it's still not the ideal solution, the ```withdraw_funding``` takes care of returning the oracle reward to the creator in case the funding period expired. 
If the current stage is ```FailedBountyWithdrawal``` and the funding period expired, I know that there were contributors because it's the only situation possible for this extrinsic. So the last contributor returns the reward.
```rust
            if Self::withdrawal_completed(&current_bounty_stage, &bounty_id) {
                if let Some(_) = Self::is_funding_expired(&bounty){
                    Self::return_bounty_oracle_reward_to_creator(bounty_id, &bounty)?;
                }
                Self::remove_bounty(&bounty_id);
            }
```

```rust
    fn is_funding_expired(bounty: &Bounty<T>,) -> Option<BountyStage> {
        // Bounty was created. There can be some contributions. Funding period is not over.
        if let BountyMilestone::Created {
            created_at,
            ..
        } = bounty.milestone.clone()
        {
            let funding_period_is_expired = match bounty.creation_params.funding_type {
                // Never expires
                FundingType::Perpetual { .. } => false,
                FundingType::Limited { funding_period, .. } => created_at + funding_period < Self::current_block(),
            };

            if funding_period_is_expired{
                return Some(BountyStage::FundingExpired);
            }
        }

        None
    }
```

**Comment by L3pereira** [comment] 2022-03-07 09:39
@shamil-gadelshin here is the test with abnormal behaviour
```rust
#[weight = Module::<T>::work_entrants_stake_account_action_weight(&stake_account_action)]
 pub fn work_entrants_stake_account_action( 
            origin,
            bounty_id: T::BountyId,
            stake_account_action: WorkEntrantStakeAccountActionMap<T::EntryId>,)

       for (entry_id, action) in stake_account_action {
             //The test will run 3 entries the second one doesn't exist, the normal behaviour 
             //should be the entire function return error, but what happens is the loop continues to the next iteration.
             let entry = Self::ensure_work_entry_exists(&entry_id)?;
             println!("{:?}", entry);
       }
}
```
```rust
#[test]
fn work_entrants_stake_account_action_fails_one_entry() {
    build_test_externalities().execute_with(|| {
        let starting_block = 1;
        run_to_block(starting_block);

        let max_amount = 500;

        let funder_amount = 500;

        let funding_account_id = 1;
        let funding_member_id = 1;

        let worker_member_id_1 = 2;
        let worker_account_id_1 = 2;

        let worker_member_id_2 = 3;
        let worker_account_id_2 = 3;

        let worker_member_id_3 = 4;
        let worker_account_id_3 = 4;

        let initial_balance = 500;
        let cherry = 200;
        let oracle_reward = 200;
        let worker_entrant_stake = 200;

        increase_account_balance(&COUNCIL_BUDGET_ACCOUNT_ID, initial_balance);
        increase_account_balance(&funding_account_id, initial_balance);
        increase_account_balance(&worker_account_id_1, initial_balance);
        increase_account_balance(&worker_account_id_2, initial_balance);
        increase_account_balance(&worker_account_id_3, initial_balance);

        CreateBountyFixture::default()
            .with_max_funding_amount(max_amount)
            .with_cherry(cherry)
            .with_oracle_reward(oracle_reward)
            .with_entrant_stake(worker_entrant_stake)
            .call_and_assert(Ok(()));

        let bounty_id = 1u64;

        FundBountyFixture::default()
            .with_origin(RawOrigin::Signed(funding_account_id))
            .with_member_id(funding_member_id)
            .with_amount(funder_amount)
            .call_and_assert(Ok(()));

        assert_eq!(
            Balances::free_balance(&worker_account_id_1),
            initial_balance
        );
        assert_eq!(
            Balances::usable_balance(&worker_account_id_1),
            initial_balance
        );

        AnnounceWorkEntryFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_1))
            .with_member_id(worker_member_id_1)
            .with_staking_account_id(worker_account_id_1)
            .with_bounty_id(bounty_id)
            .call_and_assert(Ok(()));

        let entry_id_1 = 1u64;

        let work_data = b"Work 1 submitted".to_vec();
        SubmitWorkFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_1))
            .with_member_id(worker_member_id_1)
            .with_entry_id(entry_id_1)
            .with_work_data(work_data.clone())
            .call_and_assert(Ok(()));

        AnnounceWorkEntryFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_2))
            .with_member_id(worker_member_id_2)
            .with_staking_account_id(worker_account_id_2)
            .with_bounty_id(bounty_id)
            .call_and_assert(Ok(()));

        let entry_id_2 = 2u64;

        let work_data = b"Work 2 submitted".to_vec();
        SubmitWorkFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_2))
            .with_member_id(worker_member_id_2)
            .with_entry_id(entry_id_2)
            .with_work_data(work_data.clone())
            .call_and_assert(Ok(()));

        AnnounceWorkEntryFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_3))
            .with_member_id(worker_member_id_3)
            .with_staking_account_id(worker_account_id_3)
            .with_bounty_id(bounty_id)
            .call_and_assert(Ok(()));

        let entry_id_3 = 3u64;

        let work_data = b"Work 3 submitted".to_vec();
        SubmitWorkFixture::default()
            .with_origin(RawOrigin::Signed(worker_account_id_3))
            .with_member_id(worker_member_id_3)
            .with_entry_id(entry_id_3)
            .with_work_data(work_data.clone())
            .call_and_assert(Ok(()));

        assert_eq!(
            Balances::free_balance(&worker_account_id_1),
            initial_balance
        );
        assert_eq!(
            Balances::usable_balance(&worker_account_id_1),
            initial_balance - worker_entrant_stake
        );

        TerminateBountyFixture::default()
            .with_bounty_id(bounty_id)
            .call_and_assert(Ok(()));

        WithdrawFundingFixture::default()
            .with_bounty_id(bounty_id)
            .with_member_id(funding_member_id)
            .with_origin(RawOrigin::Signed(funding_account_id))
            .call_and_assert(Ok(()));

        let slashing_share_1 = Perbill::from_percent(50);
        let stake_account_action_entry_1 = WorkEntrantStakeAccountAction {
            slashing_share: slashing_share_1,
            action_justification: Some(b"This worker failed and must be slashed 50%".to_vec()),
        };

        let slashing_share_2 = Perbill::from_percent(25);
        let stake_account_action_entry_2 = WorkEntrantStakeAccountAction {
            slashing_share: slashing_share_2,
            action_justification: Some(
                b"This worker failed a little less and must be slashed only 25%".to_vec(),
            ),
        };

        let slashing_share_3 = Perbill::from_percent(0);
        let stake_account_action_entry_3 = WorkEntrantStakeAccountAction {
            slashing_share: slashing_share_3,
            action_justification: Some(
                b"This worker failed due to unexpected circumstances and must not be slashed"
                    .to_vec(),
            ),
        };
        let invalid_entry = 5;
        let mut stake_account_action_entries = WorkEntrantStakeAccountActionMap::new();
        stake_account_action_entries.insert(entry_id_1, stake_account_action_entry_1);
        stake_account_action_entries.insert(invalid_entry, stake_account_action_entry_2.clone());
        stake_account_action_entries.insert(entry_id_3, stake_account_action_entry_3);
        //Entry 2 fails but 1 and even 3 get processed
        WorkEntrantStakeAccountActionMapFixture::default()
            .with_bounty_id(bounty_id)
            .with_stake_account_action(stake_account_action_entries)
            .call_and_assert(Err(Error::<Test>::WorkEntryDoesntExist.into()));

        let amount_slashed_1 = slashing_share_1 * worker_entrant_stake;
        let amount_slashed_2 = slashing_share_2 * worker_entrant_stake;
        let amount_slashed_3 = slashing_share_3 * worker_entrant_stake;
        assert_eq!(
            Balances::free_balance(&worker_account_id_1),
            initial_balance - amount_slashed_1
        );
        assert_eq!(
            Balances::usable_balance(&worker_account_id_1),
            initial_balance - amount_slashed_1
        );

        EventFixture::contains_crate_event(RawEvent::WorkEntrantStakeAccountAction(
            bounty_id,
            entry_id_1,
            slashing_share_1,
            amount_slashed_1,
            Some(b"This worker failed and must be slashed 50%".to_vec()),
        ));

        EventFixture::contains_crate_event(RawEvent::WorkEntrantStakeAccountAction(
            bounty_id,
            entry_id_3,
            slashing_share_3,
            amount_slashed_3,
            Some(
                b"This worker failed due to unexpected circumstances and must not be slashed"
                    .to_vec(),
            ),
        ));
        //Try again entry 2
        let mut stake_account_action_entries = WorkEntrantStakeAccountActionMap::new();
        stake_account_action_entries.insert(entry_id_2, stake_account_action_entry_2);

        WorkEntrantStakeAccountActionMapFixture::default()
            .with_bounty_id(bounty_id)
            .with_stake_account_action(stake_account_action_entries)
            .call_and_assert(Ok(()));

        EventFixture::contains_crate_event(RawEvent::WorkEntrantStakeAccountAction(
            bounty_id,
            entry_id_2,
            slashing_share_2,
            amount_slashed_2,
            Some(b"This worker failed a little less and must be slashed only 25%".to_vec()),
        ));
        EventFixture::assert_last_crate_event(RawEvent::BountyRemoved(bounty_id));
    });
}
```

**Closed as completed** 2022-04-30 18:08 UTC
Labels: enhancement, runtime, bounty-pallet
