### ISSUE TITLE
Allow querying channel's reward account

### ISSUE THREAD

**Issue by kdembler** [Joystream/joystream#4044] opened 2022-07-15 14:36 UTC
Probably include channel reward account in the `ChannelCreated` event and then index it in QN

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202613580098008) by [Unito](https://www.unito.io)

**Comment by Lezek123** [comment] 2022-07-15 14:54
Duplicate of https://github.com/Joystream/joystream/issues/4029

**Closed as completed by Lezek123** 2022-07-15 14:54 UTC
Labels: query-node, runtime

**Comment by kdembler** [comment] 2022-07-15 14:55
Oh thanks, I missed that! 🤦
